### ISSUE TITLE
New setup of PHPMyFAQ, can't create categories

### ISSUE THREAD

**Issue by woodat** [thorsten/phpMyFAQ#1089]
When going into the "Add A Category" page the "add category" button at the end of the form doesn't appear.  Enabling debug revealed nothing, but found this at the bottom of the source code:

Fatal error: Uncaught TypeError: Argument 1 passed to PMF_Perm_Medium::getAllGroupsOptions() must be of the type array, none given, called in C:\inetpub\wwwroot\admin\category.add.php on line 103 and defined in C:\inetpub\wwwroot\inc\PMF\Perm\Medium.php:664
Stack trace:
#0 C:\inetpub\wwwroot\admin\category.add.php(103): PMF_Perm_Medium->getAllGroupsOptions()
#1 C:\inetpub\wwwroot\admin\index.php(304): require('C:\\inetpub\\wwwr...')
#2 {main}
  thrown in C:\inetpub\wwwroot\inc\PMF\Perm\Medium.php on line 664

Other than enabling LDAP/SSL auth, have made no changes to the base install.  (Also can't post this on the forum because I can't register for an account.  I have no idea when you first released PHPMyFAQ)

**Comment by thorsten** [comment]
Which version do you use?

**Comment by woodat** [comment]
Just downloaded last week. 2.8.26

**Comment by thorsten** [comment]
Okay, will check it. I thought I fixed it.

**Comment by nemo656** [comment]
Hello, I am having the same problem. Tonight I downloaded phpmyfaq and set it up on my test box and everything works great except can not create categories. When I try and add a category the one thing I notice is the session will expire icon is spinning constantly. I can add news that works fine. Have stopped testing at this point because I can't add categories. I'll paste the system info.... Any help would be very appreciated. - Thank You, have a great day - Jim

phpMyFAQ Version 	2.8.26
Server Software 	Apache
Server Document root 	C:/UniServerZ/www
phpMyFAQ installation path 	C:/UniServerZ/www
PHP Version 	7.0.3
Webserver Interface 	APACHE2HANDLER
PHP Extensions Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, Phar, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, fileinfo, gd, mbstring, exif, mysqli, pdo_mysql, sockets, xmlrpc, com_dotnet
PHP Session path 	C:/UniServerZ/tmp
Database Server 	mysqli
Database Server Version 	5.6.29
Database Client Version 	mysqlnd 5.0.12-dev

**Comment by thorsten** [comment]
I think it should be fixed by adding an empty array here:

https://github.com/thorsten/phpMyFAQ/blob/2.8/phpmyfaq/admin/category.add.php#L103

So

`<?php echo $user->perm->getAllGroupsOptions() ?>`

should be

`<?php echo $user->perm->getAllGroupsOptions(array()) ?>`

**Comment by nemo656** [comment]
Thank you, just made the edit and that looks like it did the trick. I can now add categories. My testing continues. Your my hero today!!!  :)

Have a great day
Jim

**Comment by thorsten** [comment]
Okay, preparing a 2.8.27 release the next days. Thanks!

**Comment by nemo656** [comment]
Not sure this is the right place but I found two more issues during my testing. One, during guest or a logged in user other than admin when leaving a comment the saving progress bar stay up indefinitely, if you a do a refresh of the page you see the comment has been posted. Two and this issue maybe me not having seen some configuration setting yet, but it appears that a guest or a logged in user can not down load an attachment it says.... WHOA! Just went back to my test box and it shows no categories and no users, very strange. will have to try and see about this.... If I log in as administrator I see the categories and users if I log out I see no categories or news or users. Weird. I will wipe it clean and try and new install at home after work.

**Comment by thorsten** [comment]
Please create for each bug a new issue here and I'll fix them asap. Attachment downloads for guests will be possible with 2.9, there's a release candidate soon.

**Comment by thorsten** [comment]
Fixed for 2.8.27
