### ISSUE TITLE
LDAP fail

### ISSUE THREAD

**Issue by gabrielvilareal** [thorsten/phpMyFAQ#1325]
On version 2.9.7, an old issue came back: 

https://github.com/thorsten/phpMyFAQ/issues/1151
https://github.com/thorsten/phpMyFAQ/issues/1130

**Comment by thorsten** [comment]
@gabrielvilareal please check 2.9.8, released today.

**Comment by gabrielvilareal** [comment]
hi @thorsten

I tried to install version 2.9.8 but it doesn't work. I think that there are missing libs on directory inc/libs/   


![1325](https://user-images.githubusercontent.com/1303885/28234231-bcb953de-68d3-11e7-98ad-d81e56c16ee6.png)

Anyway, I looked at inc/PMF/Ldap.php and ```constant``` still there on line  number 120:

```
                if (!ldap_set_option($this->ds, constant($key), $value)) {
``` 

The solution I did in a system we have installed was to remove this ```constant``` function: 

```
                if (!ldap_set_option($this->ds, $key, $value)) {
```

**Comment by thorsten** [comment]
First, I see the files in the ZIP package:
![bildschirmfoto 2017-07-16 um 20 22 50](https://user-images.githubusercontent.com/45284/28250275-972ef456-6a64-11e7-8180-86bad5725819.png)

I'll fix the other issue now.

**Comment by nighknight** [comment]
I am sorry to bring up this topic again, but imho this fix needs to be reverted.

From my understanding the problem is heavily connected to the values specified in `phpmyfaq/config/constants_ldap.php`:

Currently (since commit 1c099d4), the parameters are specified there as strings.
![grafik](https://user-images.githubusercontent.com/29982026/28421370-4cee8e20-6d65-11e7-88c2-b87154956e60.png)

In this case, you need to use `constant($key)` in `phpmyfaq/inc/PMF/Ldap.php`.

At the moment there are strings used in the config file, but no `constant()` in the ldap file. This is inconsistent and causes a warning on a fresh installation.

Note: I assume the problem occurred for gabrielvilareal, because an old version of `phpmyfaq/config/constants_ldap.php` has been used, specifying constants instead of strings. This typically happens as a consequence of an update where you keep the old version of the file. It happened for me as well.

**Comment by thorsten** [comment]
I will re-check this.
