### ISSUE TITLE
Privacy / legal issue (GDPR) - Displaying user data in FAQ should be Opt-In

### ISSUE THREAD

**Issue by bpcurse** [thorsten/phpMyFAQ#1696]
**Is your feature request related to a problem? Please describe.**
If a user creates a FAQ, his/her full name is displayed to the public on FAQ view and PDF download.

**Describe the solution you'd like**
Personal data should not be displayed to the public by default.The user needs to actively allow it.

**Describe alternatives you've considered**
Do not display personal data at all.

**Comment by thorsten** [comment]
I would suggest to add a checkbox to allow/disallow the display of the data in the registration form. What do you think @bpcurse?

**Comment by bpcurse** [comment]
Thank you for the quick reply.
Yes that sounds good, if it is unchecked (disallowed) by default. Should also be available in the same way, when an admin user creates new users.

**Comment by thorsten** [comment]
Okay, I would add this to v3.1 as it requires a database change.

**Comment by bpcurse** [comment]
Just wanted to add that user data is also visible in the news.
Thank you for considering these changes :+1:

**Comment by thorsten** [comment]
The hidden personal data will be implemented in the whole frontend as it’s always the same functionality.

**Comment by werkstrom** [comment]
We've had our legal dept. question allowing access to our Indian and Ukrainian colleagues for administrative purposes since they can then access user data outside of the EU/EES. We are considering a function where the user has to accept their user data being exposed to users outside of the EU/EES in order to register. Not having a lot of insight in GDPR myself I'm not sure that is "good enough" but if it is, is there a way to implement a custom registration form/text?

**Comment by thorsten** [comment]
Sorry for the late response, what do you need exactly?
