### ISSUE TITLE
Elastic Search Configuration issue

### ISSUE THREAD

**Issue by ushah001** [thorsten/phpMyFAQ#1883]
*Describe the bug**
Unable to perform configuration changes under Admin backend/ Elastic Search Configuration. 
 am using elastic search 7.9.2. 

**To Reproduce**

1. Go to admin back end --? Elastic search configuration
2. Try clicking on any of the buttons /create index/drop index etc.
. Nothing happens. 

**Expected behavior**
Buttons should work as expected and search should happen via elastic search.

**Screenshots**

![image](https://user-images.githubusercontent.com/67292745/106048855-641d8200-60b3-11eb-967b-077b5967ecd1.png)

![image](https://user-images.githubusercontent.com/67292745/106049217-e9a13200-60b3-11eb-93e7-a56e24bc4821.png)

**phpMyFAQ (please complete the following information):**

- phpMyFAQ version : 3.0.5 
- PHP version - 7
- Database - MySQL
- Elasticsearch yes/no - Yes

**Additional context**
 couldn't find any documentation to how to integrate elastic search using phpmyfaq for version 7.9.2.

**Comment by thorsten** [comment]
How does your Elasticsearch configuration file look like?

**Comment by ushah001** [comment]
elasticsearch.php under config/ looks like below
![image](https://user-images.githubusercontent.com/67292745/106190176-487baf80-6177-11eb-9496-781c617e5902.png)

**Comment by thorsten** [comment]
Please try

`$PMF_ES['type'] = 'faqs';`

for the type

**Comment by ushah001** [comment]
changed it. still nothing happens. CREATE INDEX button is not doing anything on click.

**Comment by thorsten** [comment]
Do you see an index called "phpmyfaq" if you access the Elasticsearch instance?
<img width="1099" alt="Bildschirmfoto 2021-01-29 um 06 06 49" src="https://user-images.githubusercontent.com/45284/106234076-49085a80-61f8-11eb-80b0-25292870bfae.png">

**Comment by suishaojian** [comment]
`[root@localhost ~]# cat /var/www/html/config/elasticsearch.php
<?php
$PMF_ES['hosts'] = ['127.0.0.1:9200'];
$PMF_ES['index'] = 'phpmyfaq';
$PMF_ES['type'] = 'faqs';
[root@localhost ~]# `

I configed like this and it worked.
But the problem is everytime I add a new faq , I cannot search this faq from the search bar unless I click the 'full import' button manually... 
Is there any way that can  switch into the automatic mode.
thanks .

**Comment by suishaojian** [comment]
`[root@localhost ~]# cat /var/www/html/config/elasticsearch.php`
`<?php`
`$PMF_ES['hosts'] = ['127.0.0.1:9200'];`
`$PMF_ES['index'] = 'phpmyfaq';`
`$PMF_ES['type'] = 'faqs';`
`[root@localhost ~]# `
I set the config file like this and it worked . 
But the problem is I cannot search the new added faq from the search Bar unless I click the button "full import" manually...

How can I change some configuration that can make this update automatic ...

Thanks a lot if any help.

**Comment by thorsten** [comment]
Usually if you add new FAQs it should the new FAQ into the index automatically. I'll check this.

**Comment by ushah001** [comment]
> Do you see an index called "phpmyfaq" if you access the Elasticsearch instance?
> <img alt="Bildschirmfoto 2021-01-29 um 06 06 49" width="1099" src="https://user-images.githubusercontent.com/45284/106234076-49085a80-61f8-11eb-80b0-25292870bfae.png">

Yes, I am able to see index named phpmyfaq. 

![image](https://user-images.githubusercontent.com/67292745/106621280-67e05700-6540-11eb-9c36-e6ff6757ca99.png)

**Comment by thorsten** [comment]
What version of Elasticsearch do you use?

**Comment by thorsten** [comment]
Looks like this issue: https://stackoverflow.com/questions/50820309/elasticsearch-6-rejecting-mapping-update-as-the-final-mapping-would-have-more-t

**Comment by ushah001** [comment]
7.9.2 - is it compatible with phpmyfaq ?

**Comment by thorsten** [comment]
ah, never tried with v7, currently using v6 on my test environment

**Comment by ushah001** [comment]
ok, let me try with the stackoverflow link solution.

**Comment by thorsten** [comment]
I'll check the v7 compatibility, too, but if it's a bigger change, we have to fix that in v3.1

**Comment by thorsten** [comment]
Switched the Docker based development environment to Elasticsearch v7 and it worked.
