### ISSUE TITLE
Add AD authentication support additionally

### ISSUE THREAD

**Issue by thorsten** [thorsten/phpMyFAQ#1932]
see https://forum.phpmyfaq.de/viewtopic.php?f=2&t=43083&p=81030

**Comment by thorsten** [comment]
Won't be implemented as we'll add support for Azure AD.

**Comment by mohag** [comment]
ADFS might make sense for on-site AD (AFAIK, it can do SAML and OIDC)

**Comment by thorsten** [comment]
@mohag afaik Entra ID is the preferred solution from Microsoft, isn't it?

**Comment by mohag** [comment]
> [@mohag](https://github.com/mohag) afaik Entra ID is the preferred solution from Microsoft, isn't it?

Not sure about the MS recommendations.

I mainly came across this when looking if there is (generic) SAML / OIDC support, since I want to use it with Entra ID, before seeing the specific support for it.

I was looking at the [features page](https://www.phpmyfaq.de/features/) and quickly saw LDAP under SSO (which is an extra cost option on Entra ID) and no OIDC / SAML. (From the feature page, it is not clear if the Azure AD / Entra ID support would work for a tenant without the Microsoft Entra Domain Services / AD DS addon. (Since LDAP is mentioned under that support and it is not included with Entra ID without AD DS)

(I used phpMyFAQ ~10 years ago and haven't followed all the developments and is considering a new deploy, so was doing some quick assesments)
