### ISSUE TITLE
Check/Redo file system layout

### ISSUE THREAD

**Issue by winks** [thorsten/phpMyFAQ#973]
Problem:
When installing phpMyFAQ there are many directories where the webserver needs write access which needs to be fixed before installations.
Depending on your method of upgrade, you need to take care again.

Solution:
- Not clear yet, but needing one writable directory (with subdirectories) would be better.
- Also, 3.0 would be a good time to think about the file layout in general
- not sure if `attachments` may/should be outside docroot, etc.pp

**Comment by thorsten** [comment]
Rename phpmyfaq/ to src/

**Comment by modelrailroader** [comment]
Uh, this sounds difficult. 
Due to dangerous security issues, it isn't an option to just give the whole phpmyfaq directory write acess, is it?

Okay, which directories does need write access permissions:

- /attachements
- /images
- /logs
- /data
- /config

Did I forget one?

So, as I understand it right, the simplest solution would be changing the file system layout like this:

- /write-access/files/attachements
- /write-access/files/images
- /write-access/system/logs
- /write-access/system/config
- /write-access/system/data
In this case, it's only necessary to give write access to "write-access".

**Comment by thorsten** [comment]
The folder /multisite has to be writeable as well, but I wouldn't move that one.

I would name the writeable folder "user-content" or something similar, I have to think about a good name. But this would be a simple solution. The name and the path of the folder should be stored in the "faqconfig" table to make it user configurable.

**Comment by modelrailroader** [comment]
But when it comes to updating: Is then the write-acess folder the only one which shouldn't be deleted besides from multipart and the user's theme if used?

**Comment by thorsten** [comment]
Yes, but I wouldn't touch the location of the template folder for now. I don't know if the complete transition to Twig can be done in v3.3

**Comment by thorsten** [comment]
@winks @modelrailroader please check the first commit, comments are welcome!

**Comment by modelrailroader** [comment]
@thorsten Look's good!
